[package]
name = "umbral-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
umbral-interpreter = { path = "../umbral-interpreter" }
umbral-lexer = { path = "../umbral-lexer" }
umbral-parser = { path = "../umbral-parser" }
tokio = { version = "1", features = ["full"] }